sudo: false
language: ruby

rvm:
- ruby-head
- 2.3.1
- 2.3.0
- 2.2.5
- 2.2.4
- 2.2.3
- 2.2.2
- 2.2.1
- 2.2.0
- 2.1.10
- 2.1.9
- 2.1.8
- 2.1.7
- 2.1.6
- 2.1.5
- 2.1.4
- 2.1.3
- 2.1.2
- 2.1.1
- 2.1.0
- 2.0.0
- rbx-3.60
- rbx-3.59
- jruby-head
- jruby-9.1.5.0
- jruby-9.1.4.0
- jruby-9.1.3.0
- jruby-9.1.2.0
- jruby-9.1.1.0
- jruby-9.1.0.0

cache:
- bundler

matrix:
  allow_failures:
    - rvm: jruby-head

